import streamlit as st
st.title("Bienvenido a la aplicación")
st.write("En esta aplicación, utilizaremos un modelo de Árbol de Decisión para predecir la diabetes en pacientes basándonos en ciertos síntomas.")
st.write("Navega a las diferentes secciones utilizando el menú lateral para explorar los datos, el modelo y realizar predicciones interactivas.")
st.write("## Diabetes")
st.write("En la sección 'Diabetes', puedes ver la tabla de datos de 25 pacientes con sus síntomas y resultados. También se agrupan los pacientes según sus síntomas utilizando la relación de indiscernibilidad y la zona frontera.")
st.write("## Árbol de Decisión Completo")
st.write("En la sección 'Árbol de Decisión Completo', se muestra el modelo de Árbol de Decisión entrenado, la importancia de las características y las matrices de confusión para evaluar el rendimiento del modelo.")
st.write("## Árbol de Decisión Reducto")
st.write("En la sección 'Árbol de Decisión Reducto', se presenta una versión simplificada del modelo de Árbol de Decisión, destacando las características más relevantes y eliminando las menos importantes.")
st.write("## Formulario de Diagnóstico Interactivo")
st.write("En la sección 'Formulario de Diagnóstico Interactivo', puedes ingresar los síntomas de un paciente y obtener una predicción del diagnóstico de diabetes utilizando el modelo entrenado.")
st.error("**Nota:** Esta aplicación es solo para fines educativos y no debe utilizarse como un diagnóstico médico real.")
st.info("Consulta siempre a un profesional de la salud para obtener asesoramiento médico adecuado.")
st.success("¡Gracias por visitar la aplicación!")